### ISSUE TITLE
Exported videos do not properly add in padding

### ISSUE THREAD

**Issue by miklast** [tytremblay/frc-video-splitter#14]
Padding set to 10s before/35s after.

Exported videos seem to skip or fail to properly render out anything outside the default timeset in step 1, which corrupts play in the default Windows 10 video app by freezing when attempting to skip around and having a black screen during the beginning padding section, with audio playing, and at the end padding ending the video early. The video is more playable in VLC, but shows issues with playback (first 10 seconds are skipped, video ends 35s early, first couple seconds of video has noticeable movement artifacting not present in the source video.)

Both the source video and exported videos are MP4 files. 

[Exported video example](https://drive.google.com/file/d/1SISVddzqNvmryrUEEuvPx62R314EMJSW/view?usp=sharing)

**Comment by tytremblay** [comment]
Any way you can get me the source video for this?  I'm unable to reproduce on my .mp4 recordings.

**Comment by miklast** [comment]
[Link.](https://drive.google.com/file/d/1Y2Dj_rE9ML6lq6g8BWkQGtQa6i8kNPfL/view?usp=sharing) It was downloaded from BiliBili, which is the only thing that id consider to have any impact compared to other mp4's. I dont have anything else in the correct format offhand to test though.

**Comment by tytremblay** [comment]
I downloaded this video and was able to split all 8 matches.  I'm on linux, however.

**Comment by miklast** [comment]
The videos split fine, but the playback of the split videos was the issue. Issue still persists on 0.1.1. Found some other footage to test on, it def seems to be something with this specific set of videos. Both source videos seem to vary a fair amount in their encoding properties, but only "part1" seems to have any issues.

![2020-09-14_19-18-27](https://user-images.githubusercontent.com/16172857/93157445-19303e80-f6bf-11ea-855c-22859316702a.png)

Testing out other padding lengths had [no change](https://youtu.be/kDJjkosipPQ) to the issue.
