### ISSUE TITLE
Last video is missing from export

### ISSUE THREAD

**Issue by TechplexEngineer** [tytremblay/frc-video-splitter#22]
Last finals match missing from matches table

## Steps to Reproduce (for bugs)

1. Load 2022 Waterbury District Event
2. Last match is missing
3. Compare to TBA https://www.thebluealliance.com/event/2022ctwat

## Context

![image](https://user-images.githubusercontent.com/175873/158420053-2c8f8016-9e95-412e-a939-4ef571e18968.png)
![image](https://user-images.githubusercontent.com/175873/158420512-e37eff06-1a04-4a8d-bfad-c80d0d337e2c.png)

## Your Environment

Linux Mint 20.1 based on ubuntu 20.04

**Comment by tytremblay** [comment]
should be fixed in v1.1.1
